from django.forms import ModelForm, fields
from .models import Room

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        #this generated a form automatically with all the attributes of class room like host with a drop down menu, description
        #updated and created wont be showed since those arent editable fields
        #values like user should be autogenerated depending on who is logged in that is these values should be hidden later on
        exclude = ['host', 'participants']
        # exclude these from being displayed 